# Bone X_ray Classiffication

## 1. Import

In [22]:
import pandas as pd

from sklearn.model_selection import train_test_split

## 2. Loading data

In [18]:
df = pd.read_excel('../data/dataset.xlsx')

df

,image_id,center,age,gender,hand,ulna,radius,humerus,foot,tibia,...,synovial osteochondroma,other bt,osteosarcoma,other mt,upper limb,lower limb,pelvis,frontal,lateral,oblique
0,IMG000001.jpeg,1,48,F,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,0,0
1,IMG000002.jpeg,1,12,M,0,0,0,0,0,1,...,0,0,1,0,0,1,0,1,0,0
2,IMG000003.jpeg,1,12,M,0,0,0,0,0,1,...,0,0,1,0,0,1,0,0,1,0
3,IMG000004.jpeg,1,52,M,0,0,0,0,1,0,...,0,0,1,0,0,1,0,1,0,0
4,IMG000005.jpeg,1,52,M,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3741,IMG003742.jpg,3,55,M,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3742,IMG003743.jpg,3,55,M,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
3743,IMG003744.jpg,3,55,M,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
3744,IMG003745.jpg,3,8,M,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3745,IMG003746.jpg,3,8,M,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0

In [35]:
X = df.drop(columns=['image_id', 'gender']) # Ví dụ bạn muốn dự đoán gender thì bỏ nó khỏi X
y = df['gender'] # Nhãn mục tiêu
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [30]:
X_train

,center,age,hand,ulna,radius,humerus,foot,tibia,fibula,femur,...,synovial osteochondroma,other bt,osteosarcoma,other mt,upper limb,lower limb,pelvis,frontal,lateral,oblique
2936,1,51,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
3671,2,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
1518,2,25,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
724,1,14,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
1156,1,7,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,1,49,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2738,1,41,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1187,1,5,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
1768,3,25,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,1,0
1609,2,7,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,0

In [ ]:
X_test

Tỉ lệ nhãn trong tập gốc:
 osteosarcoma
0    0.920715
1    0.079285
Name: proportion, dtype: float64

Tỉ lệ nhãn trong tập Test:
 osteosarcoma
0    0.921333
1    0.078667
Name: proportion, dtype: float64