# Bone X_ray

## 1. Import

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split

## 2. Loading data

In [36]:
df = pd.read_excel('../data/dataset.xlsx')

df_drop = df
df_drop['gender'] =  df_drop['gender'].map({'M': 1, 'F': 0})
df_drop.drop(columns=['center'], inplace=True)
df_drop

,image_id,age,gender,hand,ulna,radius,humerus,foot,tibia,fibula,...,synovial osteochondroma,other bt,osteosarcoma,other mt,upper limb,lower limb,pelvis,frontal,lateral,oblique
0,IMG000001.jpeg,48,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,0,0
1,IMG000002.jpeg,12,1,0,0,0,0,0,1,0,...,0,0,1,0,0,1,0,1,0,0
2,IMG000003.jpeg,12,1,0,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,1,0
3,IMG000004.jpeg,52,1,0,0,0,0,1,0,0,...,0,0,1,0,0,1,0,1,0,0
4,IMG000005.jpeg,52,1,0,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3741,IMG003742.jpg,55,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3742,IMG003743.jpg,55,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
3743,IMG003744.jpg,55,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
3744,IMG003745.jpg,8,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3745,IMG003746.jpg,8,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0

In [37]:
train_idx, test_idx = train_test_split(df_drop.index, test_size=0.25, random_state=42)

types = ['train' if i in train_idx else 'test' for i in df.index]

df_drop.insert(1, 'type', types)
display(df_drop.head())

,image_id,type,age,gender,hand,ulna,radius,humerus,foot,tibia,...,synovial osteochondroma,other bt,osteosarcoma,other mt,upper limb,lower limb,pelvis,frontal,lateral,oblique
0,IMG000001.jpeg,test,48,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,0,0
1,IMG000002.jpeg,train,12,1,0,0,0,0,0,1,...,0,0,1,0,0,1,0,1,0,0
2,IMG000003.jpeg,train,12,1,0,0,0,0,0,1,...,0,0,1,0,0,1,0,0,1,0
3,IMG000004.jpeg,train,52,1,0,0,0,0,1,0,...,0,0,1,0,0,1,0,1,0,0
4,IMG000005.jpeg,train,52,1,0,0,0,0,1,0,...,0,0,1,0,0,1,0,0,0,1